SELECT EERDIST.CODE_COMBINATION_ID,
       EERDIST.EXPENSE_DIST_ID,
       EERDIST.EXPENSE_REPORT_ID,
       EERDIST.PJC_PROJECT_ID,
       EERDIST.PJC_TASK_ID,
       EERDIST.REIMBURSABLE_AMOUNT,
       EERDIST.COST_CENTER,
       FVTV.DESCRIPTION AS COST_CENTER_NAME,
       EXP.ASSIGNMENT_ID,
       EXP.DESCRIPTION,
       EXP.EXPENSE_ID,
       EXP.EXPENSE_REPORT_ID AS EXPENSE_REPORT_ID1,
       EXP.PERSON_ID EXPENSE_REPORT_PERSON_ID,
       EER.EXPENSE_REPORT_ID AS EXPENSE_REPORT_ID2,
       EER.EXPENSE_REPORT_NUM,
       EER.EXPENSE_STATUS_CODE,
       EER.REPORT_SUBMIT_DATE,
       EETYP.EXPENSE_TYPE_ID,
       EETYP.NAME,
       EERAPR.EVENT,
       EERAPR.EVENT_PERFORMER_ID,
       EERAPR.EVENT_DATE,
       EERAPR.APPROVAL_LEVEL,
       EERAPR.EXPENSE_STATUS_CODE APPROVAL_STATUS,
       EERAPR.AUDIT_CODE,
       EERAPR.AUDIT_RETURN_REASON_CODE,
       EERAPR.EXPORT_REJECT_CODE,
       PPNFV.PERSON_ID,
       PPNFV.LIST_NAME,
       PPNFV1.PERSON_ID APPROVER_PERSON_ID,
       PPNFV1.LIST_NAME APPROVER_NAME,
       GCC.SEGMENT1
       || '.'
       || GCC.SEGMENT2
       || '.'
       || GCC.SEGMENT3
       || '.'
       || GCC.SEGMENT4
       || '.'
       || GCC.SEGMENT5
       || '.'
       || GCC.SEGMENT6
       || '.'
       || GCC.SEGMENT7
       || '.'
       || GCC.SEGMENT8
       || '.'
       || GCC.SEGMENT9
       || '.'
       || GCC.SEGMENT10 AS CONCAT_SEGMENT
       --PPAV.SEGMENT1 AS PROJECT_NUMBER,
       --PPAV.NAME AS PROJECT_NAME
       --PPEV.ELEMENT_NUMBER AS PROJECT_TASK_NUMBER
  FROM EXM_EXPENSES EXP
  LEFT JOIN EXM_EXPENSE_REPORTS EER
ON ( EXP.EXPENSE_REPORT_ID = EER.EXPENSE_REPORT_ID )
  LEFT JOIN EXM_EXPENSE_DISTS EERDIST
ON ( EERDIST.EXPENSE_REPORT_ID = EXP.EXPENSE_REPORT_ID
   AND EERDIST.EXPENSE_ID = EXP.EXPENSE_ID )
  LEFT JOIN EXM_EXPENSE_TYPES EETYP
ON EXP.EXPENSE_TYPE_ID = EETYP.EXPENSE_TYPE_ID
  LEFT JOIN PER_PERSON_NAMES_F_V PPNFV
ON EXP.PERSON_ID = PPNFV.PERSON_ID
  LEFT JOIN EXM_EXP_REP_PROCESSING EERAPR
ON EXP.EXPENSE_REPORT_ID = EERAPR.EXPENSE_REPORT_ID
  LEFT JOIN PER_PERSON_NAMES_F_V PPNFV1
ON EERAPR.EVENT_PERFORMER_ID = PPNFV1.PERSON_ID
  LEFT JOIN GL_CODE_COMBINATIONS GCC
ON GCC.CODE_COMBINATION_ID = EERDIST.CODE_COMBINATION_ID
  LEFT JOIN FND_VS_TYPED_VALUES_VL FVTV
ON ( FVTV.VALUE = EERDIST.COST_CENTER
   AND FVTV.VALUE_SET_CODE IN ( 'Organization Rice' ) )
  WHERE EER.EXPENSE_STATUS_CODE IN ( 'PENDING_AUDIT',
                                    'PEND_IND_APPROVAL',
                                    'PEND_MGR_APPROVAL' )
   AND PPNFV1.LIST_NAME <> 'ONE, EXPENSEAUDITOR'
   AND EERAPR.EVENT_PERFORMER_ID = '300000014069429'   


--C 300000013799489 STEPHAINE POST
-- 300000563831735 JOE

---378627 300000014069429 KAZIMIR KARWOWSKI EXP001037793231