SELECT
    EXM_CREDIT_CARD_TRXNS.CREDIT_CARD_TRXN_ID,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_ADDRESS1,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_CITY,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_COUNTRY,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_NAME1,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_PROVINCE_STATE,
    EXM_CREDIT_CARD_TRXNS.MERCHANT_POSTAL_CODE,
    EXM_CREDIT_CARD_TRXNS.TRANSACTION_AMOUNT
    || ' '
    || EXM_CREDIT_CARD_TRXNS.BILLED_CURRENCY_CODE,
    TO_CHAR(EXM_CREDIT_CARD_TRXNS.TRANSACTION_DATE, 'MM/DD/YYYY'),
    EXM_EXPENSES.ASSIGNMENT_ID,
    EXM_EXPENSES.PERSON_ID,
    EXM_EXPENSE_REPORTS.EXPENSE_REPORT_ID,
    PER_ALL_PEOPLE_F.PERSON_NUMBER,
    PER_EMAIL_ADDRESSES.EMAIL_ADDRESS                                                EMAIL_ADDRESS,
    PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_NAME,
    PER_PERSON_NAMES_F_V.FULL_NAME,
    PER_PERSON_NAMES_F_V.KNOWN_AS,
    PER_ASSIGNMENT_STATUS_TYPES_TL.USER_STATUS                                       ASSIGNMENT_STATUS,
    TO_DATE(SYSDATE) - TO_DATE(EXM_CREDIT_CARD_TRXNS.TRANSACTION_DATE, 'yyyy-MM-dd') DAYS_OUTSTANDING
FROM
    EXM_CREDIT_CARD_TRXNS
    JOIN EXM_EXPENSES
    ON EXM_CREDIT_CARD_TRXNS.CREDIT_CARD_TRXN_ID=EXM_EXPENSES.CREDIT_CARD_TRXN_ID
    LEFT JOIN EXM_EXPENSE_REPORTS
    ON ( EXM_EXPENSE_REPORTS.EXPENSE_REPORT_ID = EXM_EXPENSES.EXPENSE_REPORT_ID
    AND EXM_EXPENSE_REPORTS.EXPENSE_STATUS_CODE <> 'APPROVAL_COMPLETE' )
    JOIN PER_ALL_PEOPLE_F
    ON PER_ALL_PEOPLE_F.PERSON_ID=EXM_EXPENSES.PERSON_ID
    AND ( SYSDATE BETWEEN PER_ALL_PEOPLE_F.EFFECTIVE_START_DATE
    AND PER_ALL_PEOPLE_F.EFFECTIVE_END_DATE)
    JOIN PER_PERSON_NAMES_F_V
    ON ( ( EXM_EXPENSES.PERSON_ID=PER_PERSON_NAMES_F_V.PERSON_ID)
    AND ( SYSDATE BETWEEN PER_PERSON_NAMES_F_V.EFFECTIVE_START_DATE
    AND PER_PERSON_NAMES_F_V.EFFECTIVE_END_DATE))
    JOIN PER_ALL_ASSIGNMENTS_M
    ON ( PER_ALL_ASSIGNMENTS_M.PERSON_ID=PER_ALL_PEOPLE_F.PERSON_ID
    AND ( SYSDATE BETWEEN PER_ALL_ASSIGNMENTS_M.EFFECTIVE_START_DATE
    AND PER_ALL_ASSIGNMENTS_M.EFFECTIVE_END_DATE)
    AND ( PER_ALL_ASSIGNMENTS_M.EFFECTIVE_LATEST_CHANGE='Y')
    AND ( PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_TYPE IN ('E',
    'C',
    'N',
    'P'))
    AND ( PER_ALL_ASSIGNMENTS_M.PRIMARY_FLAG='Y'))
    JOIN PER_ASSIGNMENT_STATUS_TYPES_TL
    ON PER_ASSIGNMENT_STATUS_TYPES_TL.ASSIGNMENT_STATUS_TYPE_ID=PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_STATUS_TYPE_ID
    LEFT JOIN PER_EMAIL_ADDRESSES
    ON ( PER_EMAIL_ADDRESSES.PERSON_ID =PER_ALL_ASSIGNMENTS_M.PERSON_ID
    AND PER_EMAIL_ADDRESSES.EMAIL_TYPE ='W1')
WHERE
    PER_ALL_PEOPLE_F.PERSON_NUMBER IS NOT NULL
 --AND PER_PERSON_NAMES_F_V.FULL_NAME IN ( 'Atkinson, Michelle L')
    AND (EXM_EXPENSES. EXPENSE_REPORT_ID IS NULL
    OR EXM_EXPENSE_REPORTS.EXPENSE_STATUS_CODE NOT IN ('APPROVAL_COMPLETE', 'INVOICED', 'INVOICE_CANCELED', 'PARTIAL_PAID', 'PAID' ) )
    AND (TO_DATE(SYSDATE) - TO_DATE(EXM_CREDIT_CARD_TRXNS.TRANSACTION_DATE, 'yyyy-MM-dd')) > COALESCE(TO_NUMBER(:P_NUMBER_OF_DAYS), 1)
ORDER BY
    PER_ALL_PEOPLE_F.PERSON_NUMBER ASC,
    EXM_CREDIT_CARD_TRXNS.TRANSACTION_DATE DESC