SELECT
	FND_VS_VALUES_VL.VALUE                                      COST_CENTER_CODE,
	FND_VS_VALUES_VL.DESCRIPTION                                COST_CENTER_DESC,
	PER_PERSON_NAMES_F_V.FULL_NAME,
	PER_PERSON_NAMES_F_V.KNOWN_AS,
	PER_ALL_PEOPLE_F.PERSON_NUMBER,
	PER_EMAIL_ADDRESSES.EMAIL_ADDRESS                           EMAIL_ADDRESS,
	PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_NAME,
	PER_ASSIGNMENT_STATUS_TYPES_TL.USER_STATUS                  ASSIGNMENT_STATUS,
	CARD_STATUS.MEANING                                         CARD_STATUS,
	MANAGER_NAME.FULL_NAME                                      LINE_MANAGER,
	MANAGER_EMAIL.EMAIL_ADDRESS                                 LINE_MANAGER_EMAIL,
	EXM_EXPENSE_REPORTS.PURPOSE,
	NVL(EXPENSE_STATUS.MEANING, 'Report not created')           EXPENSE_STATUS_CODE,
	EXM_EXPENSE_TYPES.NAME                                      EXPENSE_TYPE,
	EXM_EXPENSES.MERCHANT_NAME,
	SUM(EXM_EXPENSES.RECEIPT_AMOUNT)                            TOTAL_AMOUNT,
	TO_CHAR(EXM_EXPENSES.START_DATE, 'MM-DD-YYYY')              CREATION_DATE,
	TO_CHAR(EXM_EXPENSE_REPORTS.CREATION_DATE, 'MM-DD-YYYY')    REPORT_CREATION_DATE,
	TO_CHAR(EXM_EXPENSE_REPORTS.LAST_UPDATE_DATE, 'MM-DD-YYYY') REPORT_LAST_UPDATE_DATE,
	PER_ALL_ASSIGNMENTS_M.EXPENSE_CHECK_ADDRESS,
	EXM_EXPENSE_REPORTS.PAYMENT_METHOD_CODE
 --NVL(EXM_EXPENSE_REPORTS.EXPENSE_REPORT_NUM,'Unsubmitted') EXPENSE_REPORT_NUMBER,
 --EXM_EXPENSES.DESCRIPTION LINE_DESCRIPTION,
 --RECEIPTS_STATUS.MEANING RECEIPTS_STATUS_CODE,
FROM
	EXM_EXPENSES
	JOIN EXM_CREDIT_CARD_TRXNS
	ON EXM_CREDIT_CARD_TRXNS.CREDIT_CARD_TRXN_ID=EXM_EXPENSES.CREDIT_CARD_TRXN_ID
	JOIN EXM_CARDS
	ON EXM_CARDS.CARD_ID=EXM_EXPENSES.CARD_ID
	JOIN EXM_EXPENSE_DISTS
	ON EXM_EXPENSE_DISTS.EXPENSE_ID=EXM_EXPENSES.EXPENSE_ID
	LEFT JOIN GL_CODE_COMBINATIONS
	ON GL_CODE_COMBINATIONS.CODE_COMBINATION_ID=EXM_EXPENSE_DISTS.CODE_COMBINATION_ID
	JOIN EXM_EXPENSE_TYPES
	ON EXM_EXPENSE_TYPES.EXPENSE_TYPE_ID=EXM_EXPENSES.EXPENSE_TYPE_ID
	LEFT JOIN EXM_EXPENSE_REPORTS
	ON EXM_EXPENSE_REPORTS.EXPENSE_REPORT_ID=EXM_EXPENSES.EXPENSE_REPORT_ID
	JOIN PER_ALL_PEOPLE_F
	ON PER_ALL_PEOPLE_F.PERSON_ID=EXM_EXPENSES.PERSON_ID
	AND (SYSDATE BETWEEN PER_ALL_PEOPLE_F.EFFECTIVE_START_DATE
	AND PER_ALL_PEOPLE_F.EFFECTIVE_END_DATE)
	JOIN PER_PERSON_NAMES_F_V
	ON EXM_EXPENSES.PERSON_ID=PER_PERSON_NAMES_F_V.PERSON_ID
	AND (SYSDATE BETWEEN PER_PERSON_NAMES_F_V.EFFECTIVE_START_DATE
	AND PER_PERSON_NAMES_F_V.EFFECTIVE_END_DATE)
	JOIN PER_ALL_ASSIGNMENTS_M
	ON PER_ALL_ASSIGNMENTS_M.PERSON_ID=PER_ALL_PEOPLE_F.PERSON_ID
	AND (SYSDATE BETWEEN PER_ALL_ASSIGNMENTS_M.EFFECTIVE_START_DATE
	AND PER_ALL_ASSIGNMENTS_M.EFFECTIVE_END_DATE)
	AND (PER_ALL_ASSIGNMENTS_M.EFFECTIVE_LATEST_CHANGE='Y')
	AND (PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_TYPE IN ('E',
	'C',
	'N',
	'P'))
	AND (PER_ALL_ASSIGNMENTS_M.PRIMARY_FLAG='Y')
	LEFT JOIN PER_ASSIGNMENT_STATUS_TYPES_TL
	ON PER_ASSIGNMENT_STATUS_TYPES_TL.ASSIGNMENT_STATUS_TYPE_ID=PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_STATUS_TYPE_ID
	LEFT JOIN PER_ASSIGNMENT_SUPERVISORS_F
	ON PER_ASSIGNMENT_SUPERVISORS_F.ASSIGNMENT_ID=PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_ID
	AND (SYSDATE BETWEEN PER_ASSIGNMENT_SUPERVISORS_F.EFFECTIVE_START_DATE
	AND PER_ASSIGNMENT_SUPERVISORS_F.EFFECTIVE_END_DATE)
	AND PER_ASSIGNMENT_SUPERVISORS_F.MANAGER_TYPE='LINE_MANAGER'
	LEFT JOIN PER_PERSON_NAMES_F_V MANAGER_NAME
	ON MANAGER_NAME.PERSON_ID=PER_ASSIGNMENT_SUPERVISORS_F.MANAGER_ID
	AND (SYSDATE BETWEEN MANAGER_NAME.EFFECTIVE_START_DATE
	AND MANAGER_NAME.EFFECTIVE_END_DATE)
	LEFT JOIN PER_EMAIL_ADDRESSES MANAGER_EMAIL
	ON MANAGER_EMAIL.PERSON_ID=PER_ASSIGNMENT_SUPERVISORS_F.MANAGER_ID
	AND MANAGER_EMAIL.EMAIL_TYPE='W1'
	LEFT JOIN PER_EMAIL_ADDRESSES
	ON PER_EMAIL_ADDRESSES.PERSON_ID=PER_ALL_ASSIGNMENTS_M.PERSON_ID
	AND PER_EMAIL_ADDRESSES.EMAIL_TYPE='W1'
	JOIN FND_VS_VALUES_VL
	ON FND_VS_VALUES_VL.VALUE=NVL(EXM_EXPENSE_DISTS.COST_CENTER,
	EXM_EXPENSES.EMP_DEFAULT_COST_CENTER)
	AND FND_VS_VALUES_VL.ATTRIBUTE_CATEGORY='Organization Rice'
	LEFT JOIN FND_LOOKUP_VALUES_TL RECEIPTS_STATUS
	ON RECEIPTS_STATUS.LOOKUP_CODE=EXM_EXPENSE_REPORTS.RECEIPTS_STATUS_CODE
	AND RECEIPTS_STATUS.LOOKUP_TYPE='EXM_ORIGINAL_RECEIPT_STATUS'
	LEFT JOIN FND_LOOKUP_VALUES_TL EXPENSE_STATUS
	ON EXPENSE_STATUS.LOOKUP_CODE=EXM_EXPENSE_REPORTS.EXPENSE_STATUS_CODE
	AND EXPENSE_STATUS.LOOKUP_TYPE='EXM_REPORT_STATUS'
	LEFT JOIN FND_LOOKUP_VALUES_TL AUDITS
	ON AUDITS.LOOKUP_CODE=EXM_EXPENSE_REPORTS.AUDIT_CODE
	AND AUDITS.LOOKUP_TYPE = 'EXM_AUDIT_CODE'
	LEFT JOIN FND_LOOKUP_VALUES_TL CARD_STATUS
	ON CARD_STATUS.LOOKUP_CODE=EXM_CARDS.CARD_STATUS_CODE
	AND CARD_STATUS.LOOKUP_TYPE = 'EXM_CC_CARD_STATUS_CODE'
	LEFT JOIN HR_ORGANIZATION_INFORMATION_F
	ON HR_ORGANIZATION_INFORMATION_F.ORGANIZATION_ID=EXM_EXPENSES.ORG_ID
	AND (SYSDATE BETWEEN HR_ORGANIZATION_INFORMATION_F.EFFECTIVE_START_DATE
	AND HR_ORGANIZATION_INFORMATION_F.EFFECTIVE_END_DATE)
	AND HR_ORGANIZATION_INFORMATION_F.ORG_INFORMATION_CONTEXT='FUN_BUSINESS_UNIT'
	LEFT JOIN XLE_ENTITY_PROFILES
	ON XLE_ENTITY_PROFILES.LEGAL_ENTITY_ID=HR_ORGANIZATION_INFORMATION_F.ORG_INFORMATION2
WHERE
	1=1
	AND EXM_EXPENSES.RECEIPT_AMOUNT >0
	AND (TRUNC(SYSDATE)-TRUNC(TO_DATE(TO_CHAR(EXM_EXPENSES.START_DATE, 'YYYY-MM-DD'), 'YYYY-MM-DD'))>COALESCE(TO_NUMBER(:P_NUMBER_OF_DAYS), 1))
	AND (NVL(EXPENSE_STATUS.MEANING, 'Report not created')=('Report not created'))
	AND ( (FND_VS_VALUES_VL.VALUE
	       ||'-'
	       || FND_VS_VALUES_VL.DESCRIPTION) = :P_COST_CENTER
	OR :P_COST_CENTER IS NULL)
	AND (PER_ALL_PEOPLE_F.PERSON_NUMBER = :P_PERSON_NUMBER
	OR :P_PERSON_NUMBER IS NULL)
	AND (PER_ASSIGNMENT_STATUS_TYPES_TL.USER_STATUS = :P_ASSIGNMENT_STATUS
	OR :P_ASSIGNMENT_STATUS IS NULL)
	AND (NVL(EXPENSE_STATUS.MEANING, 'Report not created') = :P_REPORT_STATUS
	OR :P_REPORT_STATUS IS NULL)
	AND (CARD_STATUS.MEANING = :P_CARD_STATUS
	OR :P_CARD_STATUS IS NULL)
	AND (TO_CHAR(TO_DATE(EXM_EXPENSES.START_DATE, 'YYYY-MM-DD'), 'YYYY-MM-DD') = :P_ITEM_DATE
	OR :P_ITEM_DATE IS NULL)
GROUP BY
	FND_VS_VALUES_VL.VALUE,
	FND_VS_VALUES_VL.DESCRIPTION,
	PER_PERSON_NAMES_F_V.FULL_NAME,
	PER_PERSON_NAMES_F_V.KNOWN_AS,
	PER_ALL_PEOPLE_F.PERSON_NUMBER,
	PER_EMAIL_ADDRESSES.EMAIL_ADDRESS,
	PER_ALL_ASSIGNMENTS_M.ASSIGNMENT_NAME,
	PER_ASSIGNMENT_STATUS_TYPES_TL.USER_STATUS,
	CARD_STATUS.MEANING,
	MANAGER_NAME.FULL_NAME,
	MANAGER_EMAIL.EMAIL_ADDRESS,
	EXM_EXPENSE_REPORTS.PURPOSE,
	NVL(EXPENSE_STATUS.MEANING, 'Report not created'),
	EXM_EXPENSE_TYPES.NAME,
	EXM_EXPENSES.MERCHANT_NAME,
	TO_CHAR(EXM_EXPENSES.START_DATE, 'MM-DD-YYYY'),
	TO_CHAR(EXM_EXPENSE_REPORTS.CREATION_DATE, 'MM-DD-YYYY'),
	TO_CHAR(EXM_EXPENSE_REPORTS.LAST_UPDATE_DATE, 'MM-DD-YYYY'),
	PER_ALL_ASSIGNMENTS_M.EXPENSE_CHECK_ADDRESS,
	EXM_EXPENSE_REPORTS.PAYMENT_METHOD_CODE
ORDER BY
	PER_ALL_PEOPLE_F.PERSON_NUMBER ASC
 -- 23-12-01  BN19 Added KNOWN_AS to data model