SELECT  
  TASK.*
FROM            FA_FUSION_SOAINFRA.WFTASK       TASK 
LEFT OUTER JOIN EXM_EXPENSE_REPORTS             EER         ON (TASK.IDENTIFICATIONKEY = TRIM(EER.EXPENSE_REPORT_ID))  
WHERE 1=1
AND TASK.COMPONENTNAME = 'FinExmWorkflowExpenseApproval'
-- AND TASK.STATE IN ('ASSIGNED','INFO_REQUESTED') 
-- AND TASK.ASSIGNEES IS NOT NULL
-- AND TASK.TASKGROUPID IS NOT NULL
-- AND OUTCOME IS NULL
-- AND EXPENSE_STATUS_CODE = 'PEND_MGR_APPROVAL' 
AND EER.EXPENSE_REPORT_NUM =:ER_ID
AND (WORKFLOWPATTERN <> 'FYI' OR WORKFLOWPATTERN IS NULL)
ORDER BY TASK.CREATEDDATE DESC