SELECT
    EE.PERSON_ID,
    PAPF.PERSON_NUMBER,
    PAAM.ASSIGNMENT_STATUS_TYPE_ID,
    ECCT.CREDIT_CARD_TRXN_ID,
    TO_CHAR(EE.RECEIPT_AMOUNT, '999,999.99')
    ||' '
    || EE.RECEIPT_CURRENCY_CODE                                "CHARGE AMOUNT",
    ECCT.POSTED_AMOUNT                                         "POSTED AMOUNT",
    (SYSDATE + (-7/24))                                        MYDATE,
    TRUNC(SYSDATE + (-7/24)) - TRUNC(ECCT.TRXN_AVAILABLE_DATE) DAYS,
    ECCT.MERCHANT_NAME1,
    TRIM(ECCT.MERCHANT_ADDRESS1)
    || ' '
    || TRIM(ECCT.MERCHANT_CITY)
    || ' '
    || TRIM(ECCT.MERCHANT_PROVINCE_STATE)
    || ' '
    || TRIM(ECCT.MERCHANT_POSTAL_CODE)
    || ' '
    || TRIM(ECCT.MERCHANT_COUNTRY)                             LOCATION,
    TRUNC(ECCT.TRANSACTION_DATE)                               "CHARGE DATE",
    TRUNC(EE.START_DATE)                                       START_DATE,
    TRUNC(EE.CREATION_DATE)                                    "POSTED DATE",
    TRUNC(ECCT.TRXN_AVAILABLE_DATE)                            TRXN_AVAILABLE_DATE,
    ' '
    || PPNF.KNOWN_AS
    || ' '
    || PPNF.LAST_NAME
    || ','                                                     "SALUTATION",
    CASE
        WHEN :P_TEST_EMAIL_ADDRESS IS NOT NULL THEN
            :P_TEST_EMAIL_ADDRESS
        ELSE
            (
                SELECT
                    NVL(PEA.EMAIL_ADDRESS,
                    'pcard@io.rice.edu')
                FROM
                    PER_EMAIL_ADDRESSES PEA
                WHERE
                    :P_TEST_EMAIL_ADDRESS IS NULL
                    AND PEA.EMAIL_TYPE = 'W1'
                    AND PEA.PERSON_ID = EE.PERSON_ID
            )
    END EMAIL_ADDRESS,
    SUBSTR(IC.CCNUMBER,
    9) "LAST 4"
FROM
    IBY_CREDITCARD        IC,
    EXM_CARDS             EC,
    PER_PERSON_NAMES_F    PPNF,
    PER_ALL_PEOPLE_F      PAPF,
    EXM_EXPENSES          EE,
    EXM_CREDIT_CARD_TRXNS ECCT,
    PER_ALL_ASSIGNMENTS_M PAAM
WHERE
    IC.INSTRID = EC.CARD_REFERENCE_ID
    AND EC.CARD_ID = EE.CARD_ID
    AND PPNF.NAME_TYPE = 'GLOBAL'
    AND PPNF.EFFECTIVE_END_DATE = TO_DATE('47121231', 'YYYYMMDD')
    AND PPNF.PERSON_ID = EE.PERSON_ID
    AND TRUNC(PAPF.EFFECTIVE_END_DATE) = TO_DATE('47121231', 'YYYYMMDD')
    AND PAAM.PERSON_ID = EE.PERSON_ID
    AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
    AND PAAM.PRIMARY_FLAG = 'Y'
    AND (SYSDATE + (-7/24)) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
    AND PAAM.ASSIGNMENT_TYPE = 'E'
    AND PAAM.ASSIGNMENT_STATUS_TYPE_ID IN (1, 2)
    AND PAPF.PERSON_ID = EE.PERSON_ID
    AND TRUNC((SYSDATE + (-7/24))) - TRUNC(ECCT.TRXN_AVAILABLE_DATE) > 30
    AND ECCT.TRANSACTION_STATUS = 'VALID'
    AND ECCT.CREDIT_CARD_TRXN_ID = EE.CREDIT_CARD_TRXN_ID
    AND EE.EXPENSE_CREATION_METHOD_CODE = 'CCUPLOAD'
    AND EE.EXPENSE_REPORT_ID IS NULL
    AND (:P_PERSON_NUMBER IS NULL
    OR EE.PERSON_ID = (
        SELECT
            PERSON_ID
        FROM
            PER_ALL_PEOPLE_F PAPF2
        WHERE
            PAPF2.PERSON_NUMBER = :P_PERSON_NUMBER
            AND TRUNC(PAPF2.EFFECTIVE_END_DATE) = TO_DATE('47121231', 'YYYYMMDD')
    ))
ORDER BY
    EE.PERSON_ID,
    SUBSTR(IC.CCNUMBER, 9),
    EE.START_DATE




   SELECT
    V72673585.LOOKUP_CODE AS C164164071,
    V72673585.MEANING AS C389230568,
    V72673585.LANGUAGE AS C343259318,
    V72673585.LOOKUP_TYPE AS C417433804,
    V72673585.VIEW_APPLICATION_ID AS C456636657,
    V72673585.SET_ID AS C497682495
FROM
    FND_LOOKUP_VALUES_TL V72673585
WHERE
    ( ( ( V72673585.LOOKUP_TYPE = 'EXM_REPORT_STATUS' ) )
    AND ( ( V72673585.VIEW_APPLICATION_ID = 0 ) )
    AND ( ( V72673585.SET_ID = 0 ) )
    AND ( ( V72673585.LANGUAGE = 'US' ) )
    AND ( ( ( V72673585.LOOKUP_CODE = 'APPROVAL_COMPLETE' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'APPROVAL_REQUIRES_RECEIPTS' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'ERROR' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'HOLD_PEND_RECEIPTS' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'IND_REJECTED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'INVOICED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'INVOICE_CANCELED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'MGR_REJECTED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'PARTIAL_PAID' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'PENDING_AUDIT' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'PEND_IND_APPROVAL' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'PEND_IND_RESPONSE' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'PEND_MGR_APPROVAL' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'REQUEST_INFO' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'RETURNED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'SAVED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'SUBMITTED' ) )
    OR ( ( V72673585.LOOKUP_CODE = 'WITHDRAWN' ) ) ) )) T288378)