SELECT
    PAH.OBJECT_ID,
    PAH.OBJECT_TYPE_CODE,
    PAH.NOTE,
    PAH.PERFORMER_ID,
    PAH.PARENT_VERSION_ID,
    PAH.NOTE_MESSAGE_CODE_FLAG,
    PAH.ACTION_LEVEL,
    PAH.ASSIGNMENT_DATE,
    PAH.ACTION_DATE,
    PAH.REQUEST_ID,
    PAH.ACTION_CODE,
    PAH.CREATION_DATE,
    PAH.CREATED_BY,
    PAH.ROLE_CODE,
    INV.PO_HEADER_ID,
    COUNT(DISTINCT INV.INVOICE_ID)                                                                                                 EVENT_COUNT,
    INV.INVOICE_ID,
    INV.INVOICE_NUM,
    PPNFV.DISPLAY_NAME,
    DECODE(PAH.CREATED_BY, 'FIN_Scheduler_svc', 'FIN Scheduler', 'FUSION_APPS_PRC_SOA_APPID', 'FIN Scheduler', PPNFV.DISPLAY_NAME) CREATED_BY_NAME
FROM
    FUSION.PO_ACTION_HISTORY PAH
    JOIN FUSION.AP_INVOICES_ALL INV
    ON PAH."OBJECT_ID" = INV."PO_HEADER_ID"
    LEFT JOIN PER_USERS PU
    ON PAH.CREATED_BY = PU.USERNAME
    LEFT JOIN PER_PERSON_NAMES_F_V PPNFV
    ON ( ( PU.PERSON_ID=PPNFV.PERSON_ID)
    AND ( SYSDATE BETWEEN PPNFV.EFFECTIVE_START_DATE
    AND PPNFV.EFFECTIVE_END_DATE)
    AND PPNFV.NAME_TYPE ='GLOBAL')
WHERE
    PAH.ACTION_CODE LIKE 'INV%'
 --AND     PAH.CREATED_BY  <> 'FUSION_APPS_PRC_SOA_APPID'
    AND ( LEAST(:P_USERID) IS NULL
    OR PAH.CREATED_BY IN (:P_USERID))
    AND ( LEAST(:P_EVENT_DT_FROM) IS NULL
    OR PAH.ACTION_DATE >= TO_DATE(:P_EVENT_DT_FROM, 'YYYY-MM-DD'))
    AND ( LEAST(:P_EVENT_DT_TO) IS NULL
    OR PAH.ACTION_DATE <= TO_DATE(:P_EVENT_DT_TO, 'YYYY-MM-DD'))
 --AND     INV.INVOICE_NUM ='1800312426'
GROUP BY
    PAH.OBJECT_ID,
    PAH.OBJECT_TYPE_CODE,
    PAH.NOTE,
    PAH.PERFORMER_ID,
    PAH.PARENT_VERSION_ID,
    PAH.NOTE_MESSAGE_CODE_FLAG,
    PAH.ACTION_LEVEL,
    PAH.ASSIGNMENT_DATE,
    PAH.ACTION_DATE,
    PAH.REQUEST_ID,
    PAH.ACTION_CODE,
    PAH.CREATION_DATE,
    PAH.CREATED_BY,
    PAH.ROLE_CODE,
    INV.PO_HEADER_ID,
    INV.INVOICE_ID,
    INV.INVOICE_NUM,
    PPNFV.DISPLAY_NAME